
# Language/versions
language: node_js
matrix:
  include:
    - node_js: '8'
    - node_js: '10'
    - node_js: '12'

# Build only master (and pull-requests)
branches:
  only:
    - master

# Build script
before_script:
  - npm install -g grunt-cli
script: 'grunt ci'
