on:
  push:
    branches:
      - master
  pull_request:
    branches: # Run actions when a PR is pushed based on one of these branches
      - master

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: 12.x
          - node-version: 14.x
          - node-version: 16.x

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
